import type { ReactNode } from "react";
import { Footer } from "./footer";
// import { Header } from "./header";
import Head from "next/head";


type Props = {
  children: ReactNode;
};

export const LayoutWrapper = (props: Props) => {
  return (
    <div>
      <Head>
        <title>Supabase-tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-300">
        <div className="container grid grid-rows-[auto,1fr,auto] mx-auto min-h-screen">
          {/* <Header /> */}
          {/* 
               
                <div className="flex justify-center items-end w-full">
                  <div className="relative mr-4 w-2/4 text-left md:w-full lg:w-full xl:w-1/2">
                    <label
                      htmlFor="hero-field"
                      className="text-sm leading-7 text-gray-600"
                    >
                      Placeholder
                    </label>
                    <input
                      type="text"
                      id="hero-field"
                      name="hero-field"
                      className="py-1 px-3 w-full text-base leading-8 text-gray-700 bg-gray-100 focus:bg-transparent rounded border border-gray-300 focus:border-purple-500 outline-none focus:ring-2 focus:ring-purple-200 transition-colors duration-200 ease-in-out"
                    />
                  </div>
                  <button className="inline-flex py-2 px-6 text-lg text-white bg-purple-500 hover:bg-purple-600 rounded border-0 focus:outline-none">
                    Button
                  </button>
                </div>
*/}
          <main className="px-4 text-gray-600 bg-gray-100">
            <div>{props.children}</div>
          </main>
          <Footer />
        </div>
      </div>
    </div>
  );
};